# Generated by Django 4.2.2 on 2023-07-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='data',
            new_name='date',
        ),
    ]
